submit50:
  files: &submit50_files
    - !exclude "*"
    - !include homework/chap02-homework.md
    - !include homework/chap02-homework.ipynb
    - !require homework/chap02-homework.md

check50:
  files:
    - !exclude "*"
    - !include homework/chap02-homework.md
  checks: __init__.py
